FROM php:7.1-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev

RUN docker-php-ext-install -j$(nproc) opcache zip

COPY . /hakoniwa

WORKDIR /hakoniwa

RUN bin/composer install

VOLUME /hakoniwa/public
