version: '2'

services:
  nginx:
    build: docker/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
    volumes_from:
      - app

  app:
    build:
      dockerfile: docker/app/Dockerfile.prod
      context: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - logs:/hakoniwa/logs

volumes:
  logs:
