version: '2'

services:
  nginx:
    build: docker/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
    volumes:
      - ./public:/hakoniwa/public

  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/hakoniwa
